name: 'tpch_project'
version: '1.0.0'
config-version: 2

profile: 'default'

model-paths: ["models"]
analysis-paths: ["analyses"]
test-paths: ["tests"]
seed-paths: ["seeds"]
macro-paths: ["macros"]
snapshot-paths: ["snapshots"]

target-path: "target"  # Directory where dbt will store compiled SQL files and other artifacts.
clean-targets:  # Directories dbt will clean when you run dbt clean.
  - "target"
  - "dbt_packages"

models:
  tpch_project:
    # Applies to all files under models/
    +materialized: view  # Change to 'table' if you prefer materializing as tables.
