version: 2

sources:
  - name: tpch
    database: snowflake_sample_data
    schema: tpch_sf1  # This might be 'public' or another schema where your TPC-H tables are located.
    tables:
      - name: customer
      - name: orders
      - name: lineitem
      - name: part
      - name: supplier
      - name: partsupp
      - name: nation
      - name: region
